### ISSUE TITLE
Excessive permissions not mentioned in docs (suggestion)

### ISSUE THREAD

**Issue by rakoczy** [speedball2001/identitychooser-mx#16]
The list of permissions for the extension doesn't mention the permission which must be accepted during the process of the upgrade to the Thunderbird 78 ("Have full, unrestricted access to Thunderbird, and your computer"). I don't say it is the developer's fault (I found recently that the situation is common for many extensions excluded by unexpected changes in Thunderbird 78). However, permissions are a sensitive matter... 
Thus I would expect any changes to be elaboratively explained on the Thunderbird Add-ons page.

**Comment by speedball2001** [comment]
This is an issue with porting addons to the new Thunderbird mail extensions. Since mail extensions currently don't support everything addons need (and were able to do in old versions of Thunderbird), mail extensions need to implement so-called experiments. An extension that implements an experiment has full unrestricted access to the users computer including file system access, which is the same as it was in all versions of Thunderbird before version 78.

For more details see https://thunderbird.topicbox.com/groups/addons/Tc9a1303c15d0444d/permissions

**Comment by speedball2001** [comment]
I added a comment to https://addons.thunderbird.net/en-US/thunderbird/addon/identity-chooser/.

Do you think the explanation is sufficient?

**Comment by rakoczy** [comment]
That's absolutely enough - clear and complete!

Thank you very much :-)

**Comment by 7wells** [comment]
Hello! Is it possible (mid-term) to change the need for "full access"?

[Explanation from Mozilla](https://support.mozilla.org/de/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer):
> The extension is using an older technology and has full access to Thunderbird’s internal APIs and does not need to request individual permissions. Up to Thunderbird 68 almost every add-on had this unrestricted access without specifically asking for it. Add-ons request this permission, as long as the new permission based API system does not yet offer the functionality they need. ...

So do I understand it correctly that as of now, the new permission based API system of TB does not offer the functionality needed by identitychooser-mx/?

**Comment by speedball2001** [comment]
It depends if Thunderbird provides safer API for the functionality that Identity Chooser uses. I'm not opposed to switching to better APIs if they are available, but currently there's no alternative.

Please note that addons always had full access to your computer, even in Thunderbird 1.0. Thunderbird started to warn about this in version 78 but nothing about full access has changed between version 1 and version 78. It fundamentally stayed the same.

But since Identity Chooser is open source you're free to inspect the source code yourself, build a version with the code inspected by you and use that. 

I promise that the version on addons.thunderbird.net is the same as the one available from this repository. But if you want to be 100% sure, you have options.
