### ISSUE TITLE
Mit gleichem Account antworten mit dem Mail empfangen wurde?

### ISSUE THREAD

**Issue by Garry01** [speedball2001/identitychooser-mx#29]
Moin, ich lege normal für jeden Händler eine eigene Mailadresse an. 
Bekomme ich die Mail, so wird diese in TB auch so angezeigt. Ist es möglich, die Option aufzunehmen, dass per Default so geantwortet wird, wie man angeschrieben wurde? Irgendwann mal, gab es solche Sachen. Wäre auf jeden Fall sinnvoll.

**Comment by speedball2001** [comment]
Du kannst in den Einstellungen das Auswahlmenü für die Emailadressen am Antworten-Button deaktivieren.Am 01.07.2021 14:08 schrieb Garry01 ***@***.***>:

Moin, ich lege normal für jeden Händler eine eigene Mailadresse an.

Bekomme ich die Mail, so wird diese in TB auch so angezeigt. Ist es möglich, die Option aufzunehmen, dass per Default so geantwortet wird, wie man angeschrieben wurde? Irgendwann mal, gab es solche Sachen. Wäre auf jeden Fall sinnvoll.

**Comment by 30knees** [comment]
I don't think that covers it / or is meant. At least, I have a similar question.

Thunderbird (or is it your add-on) has this option:

_If your e-mail provider supports it, Customize From Address allows you to make a one-off minor alteration to your From address without having to create a new identity in Account Settings. For example, if your From address is John Doe <john@example.com> you may want to change it to John Doe <john+doe@example.com> or John <john@example.com>._

Could your add-on be modified so that if I receive an email to 

john@example.com 

but I don't have that identity set up, it automatically uses that email address as the identity? That's eg how it works in Fastmail's mobile email client or webmail client.

I also use a dedicated email address per shop/service provider/etc. I don't create an identify for each of these.

If it's possible, I'd be happy to help fund the development.
