### ISSUE TITLE
Reply, Forward, ... either not working at all, or using another email

### ISSUE THREAD

**Issue by BaliDave** [speedball2001/identitychooser-mx#35]
As of 91.2.0, when I try to Reply, Forward, ... using buttons in the message header and select an identity, either nothing happens, or it grabs a previous email I had opened, and not the email I'm dealing with.  This is either in the viewer pane or with the email expanded in its own tab.  

I'm on Win 10 x64 w 32 GB RAM, and a long time Identity Chooser user.  Other Add-Ons are Quick Folders, Quick Filters, Signature Switch, Compact Headers, Send Later, Provider for Google Calendar, Simple Mail Redirection, Toggle Headers, and XNote++.  I only get this behavior when Identity Chooser is enabled; all fine w all others enabled.

I've made some embarassing replies to wrong emails due to this bug.  Let me know if you want me to test a fix.

**Comment by speedball2001** [comment]
Could you please check if this is still an issue with Identity Chooser 3.1?

**Comment by Maarco73** [comment]
@speedball2001 I had the same issue. The update worked for me. Thank you!

**Comment by AnotherElk** [comment]
Hello!

This is still an issue for me with Identity Chooser 3.1 and Thunderbird 91.3.0 (64-Bit) on Windows 10 21H1 Pro x64 after every start of Thunderbird. Nothing happens when trying to start, forward or reply to an email. I didn't experience the grabbing of a previous email so far.

A possible workaround is to go to the Add-on management pane and deactivate Identity Chooser, then simply activate it again, no restart of Thunderbird necessary. Then everything will work again for me.

Removing and then reinstalling the Add-on (with restarting Thunderbird afterwards respectively) doesn't help.

Feel free to let me know whether I can report or test something.

**Comment by mark-eh** [comment]
Still a problem with Identity 3.1, Tbird 91.3.2 
If I disable and re-enable Identity Chooser, it will work once. Repeating the cycle to use each time. 
Obviously too much of a pain. 
Too bad - would be really useful if it worked.

**Comment by istrasci** [comment]
Still a problem for me with Identity 3.1, TB 91.5.0.

**Comment by MoralCode** [comment]
Did this issue start happening after deleting an email account for anyone?
