### ISSUE TITLE
mailto links

### ISSUE THREAD

**Issue by martinr63** [speedball2001/identitychooser-mx#41]
when I click on a mailto link or send a mail fron an other application, the chooser doesn't popup

Output from error console:
```
IdentityChooser#initUI -- begin background.js:94:13
IdentityChooser#initUI: window: messageCompose background.js:95:13
IdentityChooser#initUI -- end background.js:121:13
```

**Comment by speedball2001** [comment]
Identity Chooser can't intercept mailto-link since Thunderbird doesn't provide any hooks into them. There's nothing I can do about that.

**Comment by MoralCode** [comment]
> Identity Chooser can't intercept mailto-link since Thunderbird doesn't provide any hooks into them. There's nothing I can do about that.

just came here because i clicked a mailto link and figured it would be nice to get a prompt with which identity to use.

One potential, somewhat hacky workaround I thought of that should work could be:
- find some way that identity-chooser can communicate with some process outside thunderbird, such as a web server or file or other form of IPC. (maybe this is sketchy to have an addon with email access be doing this)
- have a small, separate app/program running that communicates with the addon and sets itself up as a mailto: link handler
- have the user set this app as the default mailto handler
- user clicks mailto link
- program receives mailto link and sends a message to identity chooser to tell it the link that was clicked and ask it to ask the user what identity to use
- user picks identity
- main extension sets this identity (and the account it is part of) as the default account/identity for a configured period of time (like 10 sec or 1 min or something, thisll become relevant in a sec)
- send back a message to the other program to say "im ready"
- other program receives this ready signal and resends the mailto link in a way that will be received by thunderbird (may be tricky if it is the default handler of mailtos)
- thunderbird will use the default identity and account to set the value of the from address for incoming mailto links (i tried this and was able to change the from address in a mailto link i clicked by changing my defaults)
- extension sets the defaults back after the time expires



this is probably too complicated and depends on whether theres a way to send mailto links to a specific app other than the one configured to handle them. its also kind of a workaround for the fact that `From` information is explicitly to be ignored in the mailto spec (see last paragraph of [section 3](https://www.rfc-editor.org/rfc/rfc6068#section-3)) so you cant just modify the mailto link to use a particular from address.


maybe this is useful though?

**Comment by MoralCode** [comment]
seems like thunderbird will be overhauling the UI and technical debt soon https://blog.thunderbird.net/2023/02/the-future-of-thunderbird-why-were-rebuilding-from-the-ground-up/ so maybe they'll allow mailto links to be a thing

**Comment by speedball2001** [comment]
This is great news. We'll see what will be possible in the feature.
