### ISSUE TITLE
Reply-identity is not automatically chosen anymore

### ISSUE THREAD

**Issue by poisonnuke** [speedball2001/identitychooser-mx#52]
Using v3.2 in TB102 I now have to choose my identity every time I reply to an email, which is prone to error because previously it was determined on the "to" address in the mail I'm replying to, which was very convenient and the better solution. Now it happens that I click on the wrong address and all the mix-up with wrong addresses starts all over again.

**Comment by poisonnuke** [comment]
ok but that behaviour is unexpected, because "disabling" does not mean choose automatically. And the split reply-button with drop-down arrow suggests a different behaviour too. So at least the UX is now incorrect and should be corrected to represent the actual behaviour (the description of the setting should clarify the expected outcome and the button should not be split in two parts (drop-down and button).

Why was the old functionality removed in the first place? It already was "perfect"

**Comment by notrelly74** [comment]
I am experiencing same issue - no automatic selection of same address / alias.  Clicking reply button opens up drop-down with email selection - instead of opening compose reply message window with correct address (same as receipient email) preselected.

**Comment by speedball2001** [comment]
@notrelly74 You can deactivate the menu in Identity Chooser's settings.

**Comment by notrelly74** [comment]
@speedball2001 - thank you very much - it worked!  :-)
It wasn't clear for me. For anyone wondering what to do:
- navigate to Indentity Chooser menu (Toole -> Extension & themes -> (locate identity chooser) -> click 'wrench key' icon
- uncheck marked checkboxes:

![obraz](https://user-images.githubusercontent.com/64399008/193835427-8f9df1a6-6c69-479c-b9ff-0afcf2b06ef7.png)

Now it works perfectly - like before! :-)

**Comment by poisonnuke** [comment]
> @notrelly74 You can deactivate the menu in Identity Chooser's settings.

can you please answer my question, because you changed the behavior for the worse and at least an explanation would be appropriate, if not implementing the fix as mentioned.

**Comment by speedball2001** [comment]
> > @notrelly74 You can deactivate the menu in Identity Chooser's settings.
> 
> can you please answer my question, because you changed the behavior for the worse and at least an explanation would be appropriate, if not implementing the fix as mentioned.

To be honest, I have no idea what you mean. Identity Chooser has always been able to configure the Identity Chooser menu on the reply button(s).

The only thing I did was to change the default behaviour to the menu being enabled by default. This was done because in the past I got tons of emails from users asking for exactly this behaviour. 

Please note: because of internal changes in Thunderbird I had to completely re-implement Identity Chooser as a Mail Extension. Mail Extensions severly limit what addons can do in Thunderbird. I'm not completely happy with the compromises I had to make but it is what it is. 

Feel free to help out with documentation and make it easier for new users to find and unserstand the settings. I accept merge requests.

**Comment by poisonnuke** [comment]
@speedball2001 
the UX of the button is broken since the last update. It is a two-parted button, one part contains the "Reply" text and the second part contains the down-arrow. And this kind of button has an official UX, clicking on the main part with "reply" on it should always execute the default action, and clicking on the down-arrow should open the list.

Currently clicking on the main part of the button (with list-option enabled) opens the list. This is by definition incorrect and therefore a bug (and in the old version it was working like its supposed to do)

So the question is, now knowing that there are limitations: is it still possible to assign two different click-handlers to the button, one for the default and one for the list? I have no experience with Thunderbird-development and therefore no clue where the problem comes from.

**Comment by notrelly74** [comment]
> So the question is, now knowing that there are limitations: is it still possible to assign two different click-handlers to the button, one for the default and one for the list?

Yes, it is. Just follow steps mentioned in https://github.com/speedball2001/identitychooser-mx/issues/52#issuecomment-1267026328

**Comment by speedball2001** [comment]
> the UX of the button is broken since the last update. It is a two-parted button, one part contains the "Reply" text and the second part contains the down-arrow. And this kind of button has an official UX, clicking on the main part with "reply" on it should always execute the default action, and clicking on the down-arrow should open the list.

I was specifically asked to not change the appearance of the button under the hood in order to keep compatibility with other addons that use this button. 

In fact, I use a script from official Thunderbird addon support https://github.com/thundernest/addon-developer-support/tree/master/scripts/hackToolbarbutton.

The old implementation was "perfect" only because every addon fiddeled with the UI in order to make it perfect for it's own use and pretty much destroying other addons in the process.

It's a compromise but one that works for most addons.

**Comment by poisonnuke** [comment]
> The current implementation is a compromise but one that works for most addons.

ok I see the issue, I didnt know about the difficulties between multiple addons. So ok the core of the issue is in the hackToolbarButton and not in this plugin. I will contact that developer for further investigation. 

But in the meantime it would be appropriate to change the description of the settings, because it is wrong and misleading. Can you do this? Or should I create a PR?

Something like: 
"Enabled: show a list of all available identities (no auto-selection), Disabled: auto-select identity based on to-address."

**Comment by poisonnuke** [comment]
oh I see I was wrong, the hackToolbarButton DOES implement the menu-button in the correct way but you need to use it:

hackToolbarbutton.allowDefaultAction(
  window,
  "button-newmsg",
  false);


Or is there a reason for not using the DefaultAction?

**Comment by speedball2001** [comment]
Identity Chooser exists for one simple reason: If you want to create an email -- be it a new one, reply to one or forward one -- it forces you to choose the sender identity first and opens an editor with that identity preselected as the sender. hat's why it defaults to showing you the identity menu when you click on the create/reply/forward buttons. In order to let you customize Identity Chooser's behavior at least a bit you can disable Identity Chooser's menu on the buttons in its settings.

In order to implement this, Identity Chooser has to prevent the default action on these buttons. In fact, this function has been included in hackToolbarbutton just for Identity Chooser.

If I would enable the default action on reply -- as you suggest -- the whole reason to even modify the reply button is moot. Because in that case, it would not open the identity menu when the user clicks the button.

If you don't want Identity Chooser to be enabled for the reply button, please, simply disable the menu in Identity Chooser's settings. That's why there is that check box.

It's how the addon was designed and has been working for more than 10 years. The only thing that changed was the default setting for the reply button.

You may disagree with this design, but it's how thousands of users have been using it for more than a decade. 

I will not change it.
