### ISSUE TITLE
Add-on 4.2 could not be installed because it has not been verified

### ISSUE THREAD

**Issue by ha5se** [speedball2001/identitychooser-mx#67]
There are a few symptoms, probably all deriving from "unverified" status:

- thunderbird _"about:addons"_ -> find _"identity chooser"_ does not list this one
- the direct link only offers download, no direct installation possible
- about:addons _"Install Add-on From File_" throws **"could not be installed because it has not been verified"**.

[signing-and-distribution-overview](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/) states that unsigned add-ons still can be installed in developer and nightly builds -- however I would rather stay with stable.

Instead, could You please let the current version signed?

TIA  Jenő

**Comment by speedball2001** [comment]
Could you please detail step by step what you do in order to install the addon? You can install Identity Chooser directly in Thunderbird by going to Addons & Themes, then use the search box to find identity chooser and then click "Add to Thunderbird"

If you still get an error message, please provide a screenshot, that shows both the error message as well as the application window.

**Comment by ha5se** [comment]
I must apologize... when trying to reproduce the steps now, I discovered that it must have been the wrong application window, that is, instead of thunderbird, in fact I have tried to install this add-on into firefox add-on manager...
My bad. Very sad. :(
Best regards,  Jenő
